/**
 * Extended Seed Vault Database
 * Karmel's 30 Total Seeds (5 initial + 25 new from Survival Essentials)
 * All packaged 2019–2020, cool-dry storage
 */

import { SeedPacket } from "./seed-vault-types";

export const seedVaultDatabase: SeedPacket[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // ORIGINAL 5 SEEDS (from previous batch)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "seed-pumpkin-mammoth-gold",
    commonName: "Pumpkin",
    botanicalName: "Cucurbita pepo",
    variety: "Mammoth Gold",
    seedCount: 25,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    sourceUrl: "https://www.survivalessentials.com",
    daysToMaturity: 100,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam with compost",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 48,
    utahPlantingWindows: { spring: { start: "05-15", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Plant in late May after soil warms (70°F+). Mulch heavily to retain moisture in Utah's dry air.",
    harvestTiming: "Skin hardens and turns deep orange",
    harvestSeason: "September-October",
    yieldPerPlant: "1-3 large pumpkins per plant",
    canSaveSeed: true,
    seedSavingInstructions: "Allow 1–2 pumpkins to fully mature on vine. Harvest, scoop seeds, rinse, and dry on screen for 2–3 weeks.",
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    seedStorageTemperature: { min: 40, max: 50 },
    seedStorageHumidity: "Below 50%",
    cookingMethods: ["roast", "steam", "puree", "bake"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Mild, slightly sweet, creamy when cooked",
    nutritionHighlights: "High in beta-carotene, vitamin A, potassium, fiber",
    commonCuisines: ["American", "Fall/Harvest", "Soups"],
    plantingHistory: [
      {
        year: 2023,
        plantDate: "2023-06-01",
        harvestDate: "2023-09-20",
        seedsPlanted: 6,
        seedsGerminated: 5,
        plantsHarvested: 4,
        yieldObtained: "4 pumpkins, avg 8 lbs each",
        gardenerNotes: "Started in greenhouse, transplanted after last frost.",
      },
    ],
    companionPlants: ["corn", "beans", "squash"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-squash-blue-hubbard",
    commonName: "Squash",
    botanicalName: "Cucurbita maxima",
    variety: "Blue Hubbard",
    seedCount: 25,
    germinationRate: 80,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 110,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 48,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "Excellent storage squash for Utah winters—stores 3–4 months in cool cellar (35–50°F).",
    harvestTiming: "Rind hardens completely; can't pierce with fingernail",
    harvestSeason: "September-October",
    yieldPerPlant: "2–4 squashes per plant",
    canSaveSeed: true,
    seedSavingInstructions:
      "Allow squash to fully mature and harden on vine. Scoop seeds, rinse thoroughly, and dry on screens for 3–4 weeks.",
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    seedStorageTemperature: { min: 40, max: 50 },
    seedStorageHumidity: "Below 50%",
    cookingMethods: ["roast", "steam", "puree", "bake"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Dense, dry, sweet, slightly nutty",
    nutritionHighlights: "Rich in beta-carotene, vitamins C and E, potassium",
    commonCuisines: ["Fall/Winter", "Soups"],
    successStories: ["Stores excellently through winter", "Dense, flavorful flesh"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-bean-tendergreen",
    commonName: "Bean, Green Snap",
    botanicalName: "Phaseolus vulgaris",
    variety: "Tendergreen",
    seedCount: 100,
    germinationRate: 94,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 53,
    daysToGermination: 7,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining loam, moderate fertility",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 4,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-30" }, summer: { start: "07-01", end: "07-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "EXCELLENT germination (94%)! Fast growing—perfect for succession planting. Plant every 2–3 weeks.",
    harvestTiming: "Pods tender and snap cleanly; before seeds swell",
    harvestSeason: "July-September",
    yieldPerPlant: "½ lb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["steam", "blanch-freeze", "sauté", "roast"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Tender, mild, slightly sweet",
    nutritionHighlights: "Vitamins A & C, fiber, folate, plant protein",
    successStories: ["HIGH germination rate (94%)", "Very prolific producer", "Perfect for succession planting"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-bean-fava-broad-windsor",
    commonName: "Bean, Fava (Broad Bean)",
    botanicalName: "Vicia faba",
    variety: "Broad Windsor",
    seedCount: 35,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining loam",
    soilPh: { min: 6.0, max: 8.0 },
    spacingInches: 6,
    utahPlantingWindows: { fall: { start: "09-01", end: "09-30" }, spring: { start: "04-01", end: "04-30" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "NITROGEN-FIXER! Plant in fall for spring harvest, or early spring. Survives Utah winters. Great for crop rotation.",
    harvestTiming: "Pods tender when 3–4 inches long, or wait for full mature beans",
    harvestSeason: "May-June",
    yieldPerPlant: "1 lb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["steam", "boil", "roast", "stew"],
    preservationMethods: ["freeze", "dry"],
    flavorProfile: "Creamy, mild, slightly nutty when young",
    nutritionHighlights: "High protein, fiber, iron, folate",
    commonCuisines: ["Mediterranean", "Middle Eastern"],
    successStories: ["Nitrogen-fixer for garden rotation", "Overwinters in Utah", "Both young and mature beans edible"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-bean-lima-king-of-garden",
    commonName: "Bean, Lima (Butter Bean)",
    botanicalName: "Phaseolus lunatus",
    variety: "King Of The Garden (Pole)",
    seedCount: 25,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 88,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, moderately fertile loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 6,
    utahPlantingWindows: { spring: { start: "06-01", end: "06-30" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "POLE VARIETY—needs 8+ feet trellis/stakes. Warm-season; wait for 70°F+ soil. Long maturity but high yield.",
    harvestTiming: "Pods plump, beans visible but still tender",
    harvestSeason: "August-September",
    yieldPerPlant: "2–3 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["steam", "boil", "bake", "roast"],
    preservationMethods: ["freeze", "can", "dry"],
    flavorProfile: "Buttery, mild, creamy when cooked",
    nutritionHighlights: "Good protein, fiber, magnesium, potassium",
    commonCuisines: ["American Southern"],
    successStories: ["Maximizes vertical space", "Beautiful red flowers", "High yield per plant"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW 25 SEEDS (Second Batch - Survival Essentials)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "seed-lettuce-oak-leaf",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Oak Leaf",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    daysToGermination: 7,
    startIndoors: false,
    lightRequirement: "part-shade",
    waterNeeds: "moderate",
    soilType: "Rich, moist, well-draining loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 6,
    utahPlantingWindows: { spring: { start: "04-15", end: "05-31" }, fall: { start: "08-01", end: "09-15" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Cool-season crop. Plant spring and fall; bolts quickly in summer heat. Provide afternoon shade in summer.",
    harvestTiming: "Pick outer leaves when 4–6 inches, or harvest whole head",
    harvestSeason: "May-June (spring), September-October (fall)",
    yieldPerPlant: "½ lb per plant (continuous leaf harvest)",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "sauté", "wilt"],
    preservationMethods: ["freeze"],
    flavorProfile: "Tender, mild, oak-shaped leaves",
    nutritionHighlights: "Good source of vitamins K, A; folate; low calorie",
    commonCuisines: ["Salads", "Raw"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    notes: "TWO PACKETS available (another record).",
  },

  {
    id: "seed-kale-early-curly-scotch",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Early Curly Scotch",
    seedCount: 100,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    daysToGermination: 8,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining soil",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-15" }, fall: { start: "07-15", end: "08-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Very cold-hardy. Flavor improves after frost. Start indoors in spring; direct sow in late summer for fall crop.",
    harvestTiming: "Pick outer leaves; plant continues producing",
    harvestSeason: "June-July (spring), September-November (fall)",
    yieldPerPlant: "1–2 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["sauté", "steam", "roast", "raw"],
    preservationMethods: ["freeze", "dehydrate"],
    flavorProfile: "Earthy, slightly bitter, sweet after frost",
    nutritionHighlights:
      "Extremely high in vitamins K, A, C; calcium; iron; one of the most nutrient-dense vegetables",
    commonCuisines: ["Mediterranean", "Southern", "Raw salads"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-squash-early-straight-neck",
    commonName: "Squash, Summer",
    botanicalName: "Cucurbita pepo",
    variety: "Early Straight Neck",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 50,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, fertile loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 36,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" }, summer: { start: "07-01", end: "07-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Summer squash. Harvest young (6–8 inches) for tender texture. Plant succession crops for continuous harvest.",
    harvestTiming: "Pick when 6–8 inches long; tender and yellow",
    harvestSeason: "July-September",
    yieldPerPlant: "3–5 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["sauté", "roast", "steam", "grill"],
    preservationMethods: ["freeze"],
    flavorProfile: "Tender, mild, slightly sweet",
    nutritionHighlights: "Good source of vitamin C, B vitamins, manganese",
    commonCuisines: ["Mediterranean", "Summer"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-tomato-floradade",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Floradade",
    seedCount: 50,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    daysToGermination: 7,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam with compost",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 24,
    utahPlantingWindows: { spring: { start: "05-15", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Determinate (bush) variety. Shorter plant; good for containers. Heat-tolerant for Utah.",
    harvestTiming: "Pick when fully red; stop watering to concentrate flavor",
    harvestSeason: "July-September",
    yieldPerPlant: "2–3 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "sauce", "roast", "preserve"],
    preservationMethods: ["can", "freeze", "dehydrate"],
    flavorProfile: "Balanced sweet and acidity, firm texture",
    nutritionHighlights: "High in lycopene, vitamin C, potassium",
    commonCuisines: ["Italian", "American", "Salsa"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-okra-clemson-spineless",
    commonName: "Okra",
    botanicalName: "Abelmoschus esculentus",
    variety: "Clemson Spineless",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, sandy loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "06-01", end: "06-30" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Warm-season lover. Plant after soil is 70°F+. Heat-tolerant. No prickly spines (hence 'Spineless').",
    harvestTiming: "Pick young pods (3–4 inches) when still tender; become tough when large",
    harvestSeason: "August-September",
    yieldPerPlant: "½ lb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fry", "stew", "gumbo", "steam"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Mild, slightly earthy, tender when young",
    nutritionHighlights: "Good source of vitamin C, K, fiber",
    commonCuisines: ["Southern US", "Creole", "African"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-watermelon-yellow-cream-seed",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Yellow Cream Seed",
    seedCount: 25,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 85,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, sandy loam with compost",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 48,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "Long growing season (85 days). Start indoors 4–6 weeks early. Needs warmth, sun, and consistent water.",
    harvestTiming: "Melon should sound hollow when thumped; underside creamy yellow",
    harvestSeason: "August-September",
    yieldPerPlant: "1–2 large melons per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["raw", "juice", "freeze"],
    preservationMethods: ["freeze"],
    flavorProfile: "Sweet, crisp, refreshing",
    nutritionHighlights: "High water content, vitamins C and A, lycopene",
    commonCuisines: ["Summer eating", "Picnics"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-tomato-beefsteak-red",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Beefsteak Red",
    seedCount: 25,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 78,
    daysToGermination: 7,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam with lots of compost",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 36,
    utahPlantingWindows: { spring: { start: "05-10", end: "06-10" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "Indeterminate (tall vining). Needs support/stakes 6+ feet. Large fruits (1 lb+). Worth the effort for slicing.",
    harvestTiming: "Pick when fully red and slightly soft to touch",
    harvestSeason: "July-September",
    yieldPerPlant: "3–5 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "sauce", "roast", "preserve"],
    preservationMethods: ["can", "freeze"],
    flavorProfile: "Rich, complex, perfect balance of sweet and tart",
    nutritionHighlights: "Excellent lycopene, vitamin C, potassium",
    commonCuisines: ["Italian", "Slicing", "Cooking"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-turnip-purple-top",
    commonName: "Turnip",
    botanicalName: "Brassica rapa subsp. rapa",
    variety: "Purple Top",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    daysToGermination: 5,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining loam, moderate fertility",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 4,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-15" }, fall: { start: "07-15", end: "08-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Cool-season crop. Both roots and greens edible. Grows fast. Fall crop tastes better (sweeter after frost).",
    harvestTiming: "Roots 2–3 inches diameter are tender; greens anytime",
    harvestSeason: "May-June (spring), September-October (fall)",
    yieldPerPlant: "1–2 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["roast", "boil", "mash", "sauté", "raw"],
    preservationMethods: ["freeze", "store"],
    flavorProfile: "Mild, slightly sweet, creamy texture when cooked",
    nutritionHighlights: "Good vitamin C, fiber, calcium in greens",
    commonCuisines: ["Southern US", "Root cellar", "Traditional"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-squash-table-queen",
    commonName: "Squash, Winter",
    botanicalName: "Cucurbita pepo",
    variety: "Table Queen (Acorn)",
    seedCount: 25,
    germinationRate: 83,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 85,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, fertile loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 48,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Stores well (3 months in cool place). Individual-portion size. Classic acorn shape.",
    harvestTiming: "Rind hardened, dark green with orange patches",
    harvestSeason: "September-October",
    yieldPerPlant: "3–5 squashes per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "bake", "steam", "stuff"],
    preservationMethods: ["store"],
    flavorProfile: "Sweet, nutty, creamy texture",
    nutritionHighlights: "Rich beta-carotene, vitamins C and B",
    commonCuisines: ["American", "Roasted", "Stuffed"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-onion-yellow",
    commonName: "Onion",
    botanicalName: "Allium cepa",
    variety: "Yellow",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    soilType: "Well-draining, loose soil",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 4,
    utahPlantingWindows: { spring: { start: "03-01", end: "04-30" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "Long-day onion for northern climates. Start indoors 10–12 weeks early. Bulbs form mid-summer.",
    harvestTiming: "Tops fall over and dry; pull and cure in airy spot",
    harvestSeason: "July-August (cure), September (store)",
    yieldPerPlant: "1 large bulb per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["raw", "caramelize", "roast", "cook"],
    preservationMethods: ["store", "freeze"],
    flavorProfile: "Sharp when raw; sweet and mild when cooked",
    nutritionHighlights: "Good source of fiber, vitamins C and B, quercetin",
    commonCuisines: ["All", "Storage"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-bean-kidney-burgundy",
    commonName: "Bean, Kidney (Dry)",
    botanicalName: "Phaseolus vulgaris",
    variety: "Burgundy",
    seedCount: 150,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining loam, moderate fertility",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 4,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Dry bean for storage. Let pods fully mature and dry on plant before harvest.",
    harvestTiming: "Pods dried and brittle; rattle when shaken",
    harvestSeason: "September-October (harvest dry)",
    yieldPerPlant: "1 lb dry beans per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 1,
    cookingMethods: ["soak-boil", "slow-cook", "soup", "stew"],
    preservationMethods: ["store-dry"],
    flavorProfile: "Earthy, firm texture, classic bean flavor",
    nutritionHighlights: "Very high protein, fiber, iron, magnesium",
    commonCuisines: ["American", "Soups", "Stews"],
    successStories: ["MOST seeds (150)—great for succession planting or large crop"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-broccoli-green-sprouting",
    commonName: "Broccoli",
    botanicalName: "Brassica oleracea var. italica",
    variety: "Green Sprouting",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    daysToGermination: 7,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining soil with compost",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-15" }, fall: { start: "07-01", end: "08-15" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Cool-season crop. Very productive with side shoots after main head. Fall crop is often better than spring.",
    harvestTiming: "Cut main head when tight buds, 6–8 inches; side shoots continue",
    harvestSeason: "June-July (spring), September-October (fall)",
    yieldPerPlant: "1–2 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["steam", "roast", "sauté", "raw"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Mild, slightly sweet, tender when young",
    nutritionHighlights: "Extremely high vitamins C and K, calcium, fiber",
    commonCuisines: ["American", "Mediterranean", "Asian"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-cabbage-red-purple",
    commonName: "Cabbage",
    botanicalName: "Brassica oleracea var. capitata",
    variety: "Red Purple",
    seedCount: 100,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    daysToGermination: 8,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining soil",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-15" }, fall: { start: "06-15", end: "08-01" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "Stores well (months in cool cellar). Fall crop is sweeter.",
    harvestTiming: "Heads firm and dense; cut at base",
    harvestSeason: "June-July (spring), September-November (fall)",
    yieldPerPlant: "2–4 lb heads",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "coleslaw", "ferment", "steam", "stir-fry"],
    preservationMethods: ["ferment", "store", "freeze"],
    flavorProfile: "Sweet, crisp, slightly peppery",
    nutritionHighlights: "High vitamin C, fiber, antioxidants (anthocyanins in red)",
    commonCuisines: ["American", "Slaw", "Fermented"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-melon-honeydew",
    commonName: "Melon",
    botanicalName: "Cucumis melo",
    variety: "Honeydew",
    seedCount: 50,
    germinationRate: 83,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    daysToGermination: 8,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, sandy loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 36,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Warm-season. Long growing season (80 days). Start indoors 4–6 weeks early.",
    harvestTiming: "Melon slips easily from vine; fragrant",
    harvestSeason: "August-September",
    yieldPerPlant: "2–3 melons per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "juice", "freeze", "dessert"],
    preservationMethods: ["freeze"],
    flavorProfile: "Sweet, pale green flesh, delicate",
    nutritionHighlights: "Good source of vitamin C, potassium",
    commonCuisines: ["Breakfast", "Dessert", "Summer"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-carrot",
    commonName: "Carrot",
    botanicalName: "Daucus carota subsp. sativus",
    variety: "Standard",
    seedCount: 200,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    daysToGermination: 14,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Loose, well-draining, rock-free loam",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 2,
    utahPlantingWindows: { spring: { start: "04-15", end: "05-31" }, fall: { start: "07-01", end: "08-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "MOST SEEDS (200)! Slow germination (14 days). Direct sow. Fall crop tastes sweeter. Stores months in cool cellar.",
    harvestTiming: "Pull when 1/2 inch diameter at top; anytime after",
    harvestSeason: "June-July (spring), September-November (fall)",
    yieldPerPlant: "½ lb per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["raw", "steam", "roast", "juice"],
    preservationMethods: ["store", "freeze", "dehydrate"],
    flavorProfile: "Sweet, crisp when raw; mellow when cooked",
    nutritionHighlights: "Extremely high beta-carotene, vitamin A",
    commonCuisines: ["All", "Root cellar"],
    successStories: ["Most versatile vegetable", "Stores excellently", "Very productive"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-eggplant-black-beauty",
    commonName: "Eggplant",
    botanicalName: "Solanum melongena",
    variety: "Black Beauty",
    seedCount: 75,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "05-15", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Heat-lover. Needs warm soil (70°F+). Start indoors early. Slower to produce than tomatoes.",
    harvestTiming: "Pick when glossy and dark purple; before spines harden",
    harvestSeason: "August-September",
    yieldPerPlant: "1–2 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["roast", "fry", "grill", "stew"],
    preservationMethods: ["freeze", "dehydrate"],
    flavorProfile: "Creamy, mild, absorbs flavors",
    nutritionHighlights: "Good source of fiber, vitamins K and C, antioxidants",
    commonCuisines: ["Mediterranean", "Asian", "Italian"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-dill-mammoth-leaf-island",
    commonName: "Dill",
    botanicalName: "Anethum graveolens",
    variety: "Mammoth Leaf (Island)",
    seedCount: 100,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 50,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    soilType: "Well-draining loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 12,
    utahPlantingWindows: { spring: { start: "04-15", end: "06-30" }, summer: { start: "07-01", end: "08-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "Fast-growing herb. Large leaves (hence 'Mammoth'). Plant succession crops for continuous harvest.",
    harvestTiming: "Harvest leaves anytime; before flowering for best flavor",
    harvestSeason: "May-September",
    yieldPerPlant: "½ lb fresh herb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["fresh", "dry", "pickle"],
    preservationMethods: ["dry", "freeze"],
    flavorProfile: "Aromatic, slightly sweet, feathery leaves",
    nutritionHighlights: "Good source of antioxidants, minerals",
    commonCuisines: ["Scandinavian", "Russian", "Pickling"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-parsnip",
    commonName: "Parsnip",
    botanicalName: "Pastinaca sativa",
    variety: "Standard",
    seedCount: 100,
    germinationRate: 67,
    packagedDate: "2019-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    daysToGermination: 21,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Loose, deep, rock-free loam",
    soilPh: { min: 6.0, max: 8.0 },
    spacingInches: 3,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-15" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "OLDEST PACKET (2019, 7 years old). LOWEST GERM (67%)—may want to test viability. Slow, long growing season (120 days). Flavor improves after frost.",
    harvestTiming: "Roots 1 inch diameter, pull anytime after",
    harvestSeason: "October-November (improve after frost)",
    yieldPerPlant: "½ lb per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 1,
    cookingMethods: ["roast", "boil", "steam", "mash"],
    preservationMethods: ["store", "freeze"],
    flavorProfile: "Sweet, nutty, creamy texture",
    nutritionHighlights: "Good fiber, vitamin C, minerals",
    commonCuisines: ["European", "Root vegetables"],
    challenges: ["Very slow germination (21 days)", "Low germination rate—consider testing first"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-rutabaga",
    commonName: "Rutabaga (Swede)",
    botanicalName: "Brassica napus var. napobrassica",
    variety: "Standard",
    seedCount: 100,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    daysToGermination: 8,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, moderately fertile loam",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 6,
    utahPlantingWindows: { spring: { start: "04-15", end: "05-31" }, fall: { start: "06-15", end: "07-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Cool-season crop. Stores months in cool cellar. Fall crop better. Also called 'Swede' or 'Neep' in Scotland/UK.",
    harvestTiming: "Roots 3–4 inches diameter; pull when large",
    harvestSeason: "September-November (fall crop best)",
    yieldPerPlant: "1–2 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["roast", "boil", "mash", "stew"],
    preservationMethods: ["store", "freeze"],
    flavorProfile: "Sweet, creamy, slight cabbage note",
    nutritionHighlights: "Good vitamin C, fiber, potassium",
    commonCuisines: ["Scottish", "Scandinavian", "Root vegetables"],
    successStories: ["Excellent germination (91%)", "Stores extremely well", "Great for fall planting"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-swiss-chard",
    commonName: "Swiss Chard",
    botanicalName: "Beta vulgaris subsp. cicla",
    variety: "Standard (likely Rainbow)",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, fertile loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 6,
    utahPlantingWindows: { spring: { start: "04-15", end: "06-30" }, fall: { start: "07-15", end: "09-15" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Prolific, long-season leaf producer. More heat-tolerant than lettuce. Pick outer leaves; plant keeps producing.",
    harvestTiming: "Pick outer leaves when 6–8 inches long",
    harvestSeason: "June-October (near continuous)",
    yieldPerPlant: "2–3 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["sauté", "steam", "raw", "soup"],
    preservationMethods: ["freeze"],
    flavorProfile: "Mild, slightly sweet, tender leaves",
    nutritionHighlights: "Excellent vitamins A, K, C; minerals",
    commonCuisines: ["Mediterranean", "European", "Raw"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-collards-georgia-southern",
    commonName: "Collards",
    botanicalName: "Brassica oleracea var. viridis",
    variety: "Georgia Southern",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 65,
    daysToGermination: 8,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining soil",
    soilPh: { min: 6.0, max: 7.5 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "04-01", end: "05-31" }, fall: { start: "07-01", end: "08-31" } },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes:
      "Southern favorite. Very cold-hardy. Flavor improves after light frost. Long productive season.",
    harvestTiming: "Pick outer leaves; plant continues producing",
    harvestSeason: "June-July (spring), September-November (fall)",
    yieldPerPlant: "2–3 lbs per plant",
    canSaveSeed: false,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["sauté", "steam", "slow-cook"],
    preservationMethods: ["freeze"],
    flavorProfile: "Earthy, slightly sweet, tender leaves",
    nutritionHighlights: "Very high vitamins K, A, C; calcium",
    commonCuisines: ["Southern US", "Soul food"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-cucumber-marketmore",
    commonName: "Cucumber",
    botanicalName: "Cucumis sativus",
    variety: "Marketmore",
    seedCount: 50,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 68,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Well-draining, rich loam",
    soilPh: { min: 6.0, max: 7.0 },
    spacingInches: 12,
    utahPlantingWindows: { spring: { start: "05-15", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Vining type. Needs trellis or support. Dark green slicing cucumber.",
    harvestTiming: "Pick when 8–10 inches long; before yellowing",
    harvestSeason: "July-September",
    yieldPerPlant: "2–3 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "pickle", "slice"],
    preservationMethods: ["pickle"],
    flavorProfile: "Crisp, mild, few seeds",
    nutritionHighlights: "Low calorie, hydrating, vitamin K",
    commonCuisines: ["Salad", "Pickling", "Raw"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-pepper-bell-sweet",
    commonName: "Pepper, Bell",
    botanicalName: "Capsicum annuum",
    variety: "Sweet (color not specified)",
    seedCount: 50,
    germinationRate: 81,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    daysToGermination: 14,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 18,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "Heat-loving. Long growing season (90 days). Start indoors 8–10 weeks early. Slower germination (14 days).",
    harvestTiming: "Pick at any stage; green when immature, red/yellow when ripe",
    harvestSeason: "August-September",
    yieldPerPlant: "4–8 peppers per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["raw", "roast", "stuff", "fry"],
    preservationMethods: ["freeze", "dehydrate"],
    flavorProfile: "Mild, slightly sweet, crisp",
    nutritionHighlights: "Excellent vitamin C, fiber, antioxidants",
    commonCuisines: ["All", "Raw snacking"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },

  {
    id: "seed-pepper-cherry-bells",
    commonName: "Pepper, Cherry (Sweet)",
    botanicalName: "Capsicum annuum",
    variety: "Cherry Bells",
    seedCount: 200,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage - basement",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    daysToGermination: 12,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam",
    soilPh: { min: 6.0, max: 6.8 },
    spacingInches: 12,
    utahPlantingWindows: { spring: { start: "05-20", end: "06-15" } },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes:
      "Compact, ornamental pepper. Small round peppers (½–¾ inch). Very productive. 200 seeds—most in the collection!",
    harvestTiming: "Pick at any stage; bright red when fully ripe",
    harvestSeason: "August-September",
    yieldPerPlant: "20–40 peppers per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["raw", "stuff", "pickle"],
    preservationMethods: ["freeze", "pickle"],
    flavorProfile: "Mild, slightly sweet, thin-walled",
    nutritionHighlights: "Good vitamin C, smaller size = convenient",
    commonCuisines: ["Appetizers", "Snacking", "Pickling"],
    successStories: ["MOST SEEDS (200)", "Very ornamental", "Extremely prolific"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },
];
