/**
 * Complete Seed Vault Database — All 124 Packets
 * Karmel's comprehensive seed inventory across all batches
 * Packaged 2020, stored cool-dry with excellent viability (88.5% average)
 */

import { SeedPacket } from "./seed-vault-types";

export const completeSeedVaultDatabase: SeedPacket[] = [
  // ==========================================
  // BATCH 1: ORIGINAL 5 SURVIVAL ESSENTIALS
  // ==========================================

  {
    id: "seed-pumpkin-mammoth-gold-001",
    commonName: "Pumpkin",
    botanicalName: "Cucurbita pepo",
    variety: "Mammoth Gold",
    seedCount: 25,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    daysToGermination: 10,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    soilType: "Rich, well-draining loam",
    spacingInches: 48,
    utahPlantingWindows: {
      spring: { start: "05-15", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Plant late May after soil warms (70°F+). Mulch heavily. Can struggle with spider mites in greenhouse.",
    harvestTiming: "Skin hardens, turns deep orange",
    harvestSeason: "September-October",
    yieldPerPlant: "1-3 pumpkins per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "steam", "puree", "bake"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Mild, slightly sweet, creamy",
    nutritionHighlights: "High beta-carotene, vitamin A, potassium, fiber",
    commonCuisines: ["American", "Fall/Harvest"],
    companionPlants: ["corn", "beans", "squash", "nasturtiums"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-blue-hubbard-001",
    commonName: "Squash",
    botanicalName: "Cucurbita maxima",
    variety: "Blue Hubbard",
    seedCount: 25,
    germinationRate: 80,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 110,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    utahPlantingWindows: {
      spring: { start: "05-20", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "Excellent storage squash for Utah winters—stores 3-4 months in cool cellar (50°F).",
    harvestTiming: "Rind hardens completely, dull finish",
    harvestSeason: "September-October",
    yieldPerPlant: "2-4 squashes",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["roast", "steam", "puree", "bake"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Dense, dry, sweet, slightly nutty",
    nutritionHighlights: "Beta-carotene, vitamins C, E, potassium",
    commonCuisines: ["Fall/Winter", "Soups"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-tendergreen-001",
    commonName: "Bean, Green Snap",
    botanicalName: "Phaseolus vulgaris",
    variety: "Tendergreen",
    seedCount: 100,
    germinationRate: 94,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 53,
    daysToGermination: 7,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    utahPlantingWindows: {
      spring: { start: "05-20", end: "06-30" },
      summer: { start: "07-01", end: "07-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "EXCELLENT germination (94%)! Fast-growing—perfect for succession planting every 2-3 weeks.",
    harvestTiming: "Pods snap cleanly, before seeds swell",
    harvestSeason: "July-September",
    yieldPerPlant: "0.5 lb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["steam", "blanch-freeze", "sauté"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Tender, mild, slightly sweet",
    nutritionHighlights: "Vitamins A, C; fiber, folate, protein",
    commonCuisines: ["American", "Mediterranean"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-fava-broad-windsor-001",
    commonName: "Bean, Fava (Broad Bean)",
    botanicalName: "Vicia faba",
    variety: "Broad Windsor",
    seedCount: 35,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahPlantingWindows: {
      fall: { start: "09-01", end: "09-30" },
      spring: { start: "04-01", end: "04-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "NITROGEN-FIXER! Plant fall for spring harvest. Overwinters in Utah. Improves soil.",
    harvestTiming: "Pods tender at 3-4 inches, or mature beans",
    harvestSeason: "March-May (spring crop)",
    yieldPerPlant: "1 lb per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["steam", "boil", "roast", "stew"],
    preservationMethods: ["freeze", "dry"],
    flavorProfile: "Creamy, mild, slightly nutty",
    nutritionHighlights: "High protein, fiber, iron, folate",
    commonCuisines: ["Mediterranean", "Middle Eastern"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-lima-king-of-garden-001",
    commonName: "Bean, Lima (Butter Bean)",
    botanicalName: "Phaseolus lunatus",
    variety: "King Of The Garden (Pole)",
    seedCount: 25,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 88,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahPlantingWindows: {
      spring: { start: "06-01", end: "06-30" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    utahSpecificNotes: "POLE VARIETY—needs 8+ feet trellis. Wait for warm soil (70°F+). Long season but high yield.",
    harvestTiming: "Pods plump, beans visible, still tender",
    harvestSeason: "August-September",
    yieldPerPlant: "2-3 lbs per plant",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["steam", "boil", "bake"],
    preservationMethods: ["freeze", "can"],
    flavorProfile: "Buttery, mild, creamy",
    nutritionHighlights: "Good protein, fiber, magnesium",
    commonCuisines: ["American Southern"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 2: 30 SURVIVAL ESSENTIALS PACKETS
  // ==========================================

  {
    id: "seed-chicory-001",
    commonName: "Chicory",
    botanicalName: "Cichorium intybus",
    seedCount: 75,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 75,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-corn-001",
    commonName: "Corn, Sweet",
    botanicalName: "Zea mays",
    seedCount: 50,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 8,
    utahPlantingWindows: {
      spring: { start: "05-20", end: "06-30" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["boil", "grill", "roast"],
    preservationMethods: ["freeze", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-heirloom-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Heirloom",
    seedCount: 50,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    utahPlantingWindows: {
      spring: { start: "05-15", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh", "sauce", "roast"],
    preservationMethods: ["can", "freeze", "dry"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-marma-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Marma",
    seedCount: 50,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-001",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    seedCount: 50,
    germinationRate: 80,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    utahPlantingWindows: {
      spring: { start: "04-15", end: "05-30" },
      fall: { start: "06-15", end: "07-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "roast", "steam", "juice"],
    preservationMethods: ["freeze", "store-root-cellar"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-okra-three-foot-tall-001",
    commonName: "Okra",
    botanicalName: "Abelmoschus esculentus",
    variety: "Three Foot Tall",
    seedCount: 50,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahPlantingWindows: {
      spring: { start: "06-01", end: "06-30" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fry", "boil", "stew"],
    preservationMethods: ["freeze", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-pepper-hot-wax-001",
    commonName: "Pepper, Hot",
    botanicalName: "Capsicum annuum",
    variety: "Hot Wax",
    seedCount: 75,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 18,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fresh", "dry", "sauce"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-batch2-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    seedCount: 75,
    germinationRate: 92,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    utahPlantingWindows: {
      spring: { start: "04-01", end: "05-15" },
      fall: { start: "08-01", end: "09-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "salad", "wilted"],
    preservationMethods: ["freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-asparagus-new-millennium-001",
    commonName: "Asparagus",
    botanicalName: "Asparagus officinalis",
    variety: "New Millennium",
    seedCount: 75,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 180,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahPlantingWindows: {
      spring: { start: "03-15", end: "04-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["steam", "roast", "grill"],
    preservationMethods: ["freeze", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-slice-etoile-001",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    variety: "Slice Etoile",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-spinach-bloomsdale-001",
    commonName: "Spinach",
    botanicalName: "Spinacia oleracea",
    variety: "Bloomsdale",
    seedCount: 75,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 4,
    utahPlantingWindows: {
      spring: { start: "03-15", end: "04-30" },
      fall: { start: "08-15", end: "09-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "steam", "sauté"],
    preservationMethods: ["freeze", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-batch2-002",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    seedCount: 200,
    germinationRate: 93,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-batch2-003",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kohlrabi-white-vienna-001",
    commonName: "Kohlrabi",
    botanicalName: "Brassica oleracea var. gongylodes",
    variety: "White Vienna",
    seedCount: 200,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahPlantingWindows: {
      spring: { start: "04-15", end: "05-30" },
      fall: { start: "06-15", end: "07-30" },
    },
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "steam", "raw"],
    preservationMethods: ["freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-parsnip-001",
    commonName: "Parsnip",
    botanicalName: "Pastinaca sativa",
    seedCount: 75,
    germinationRate: 71,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 120,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    utahPlantingWindows: {
      spring: { start: "04-01", end: "05-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "Lower germination (71%)—use soon. Prefers cool season.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 1,
    cookingMethods: ["roast", "steam", "mash"],
    preservationMethods: ["store-root-cellar"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-chard-fordhook-giant-001",
    commonName: "Swiss Chard",
    botanicalName: "Beta vulgaris subsp. cicla",
    variety: "Fordhook Giant",
    seedCount: 400,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "part-shade",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahPlantingWindows: {
      spring: { start: "04-15", end: "05-30" },
      fall: { start: "06-15", end: "07-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    utahSpecificNotes: "MOST ABUNDANT PACKET! 400 seeds. Perfect for succession planting.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["steam", "sauté", "fresh"],
    preservationMethods: ["freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-batch2-004",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    seedCount: 150,
    germinationRate: 93,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-coriander-batch2-001",
    commonName: "Coriander",
    botanicalName: "Coriandrum sativum",
    seedCount: 50,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 50,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fresh leaves", "seeds for spice"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-lacinato-001",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Lacinato",
    seedCount: 150,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahPlantingWindows: {
      spring: { start: "04-15", end: "05-30" },
      fall: { start: "06-15", end: "07-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["steam", "sauté", "raw"],
    preservationMethods: ["freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-amaranth-red-head-001",
    commonName: "Amaranth",
    botanicalName: "Amaranthus cruentus",
    variety: "Red Head",
    seedCount: 200,
    germinationRate: 86,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    spacingInches: 12,
    utahPlantingWindows: {
      spring: { start: "05-15", end: "06-30" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["leaves-steam", "grain-cooked"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-delicata-001",
    commonName: "Squash",
    botanicalName: "Cucurbita pepo",
    variety: "Delicata",
    seedCount: 25,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    utahPlantingWindows: {
      spring: { start: "05-20", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "bake"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-delicata-002",
    commonName: "Squash",
    botanicalName: "Cucurbita pepo",
    variety: "Delicata",
    seedCount: 25,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-charleston-gray-001",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Charleston Gray",
    seedCount: 25,
    germinationRate: 92,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    utahPlantingWindows: {
      spring: { start: "05-15", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-sugar-baby-001",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Sugar Baby",
    seedCount: 25,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    utahPlantingWindows: {
      spring: { start: "05-15", end: "06-15" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-beet-batch2-001",
    commonName: "Beet",
    botanicalName: "Beta vulgaris",
    seedCount: 50,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    utahPlantingWindows: {
      spring: { start: "04-15", end: "05-30" },
      fall: { start: "06-15", end: "07-30" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "steam", "raw"],
    preservationMethods: ["pickle", "freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-delicata-003",
    commonName: "Squash",
    botanicalName: "Cucurbita pepo",
    variety: "Delicata",
    seedCount: 25,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-delicata-004",
    commonName: "Squash",
    botanicalName: "Cucurbita pepo",
    variety: "Delicata",
    seedCount: 25,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-charleston-gray-002",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Charleston Gray",
    seedCount: 25,
    germinationRate: 92,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-sugar-baby-002",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Sugar Baby",
    seedCount: 25,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-beet-batch2-002",
    commonName: "Beet",
    botanicalName: "Beta vulgaris",
    seedCount: 50,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 3: 25 SURVIVAL ESSENTIALS PACKETS
  // ==========================================

  {
    id: "seed-mustard-brown-001",
    commonName: "Mustard",
    botanicalName: "Brassica juncea",
    variety: "Brown",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 40,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahPlantingWindows: {
      spring: { start: "04-01", end: "05-15" },
      fall: { start: "08-01", end: "09-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh", "cooked", "spice"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-onion-yellow-sweet-spanish-001",
    commonName: "Onion",
    botanicalName: "Allium cepa",
    variety: "Yellow Sweet Spanish",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["fresh", "caramelize", "roast"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-rutgers-batch3-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Rutgers",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh", "sauce", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-rutgers-batch3-002",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Rutgers",
    seedCount: 60,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-chard-fordhook-batch3-001",
    commonName: "Swiss Chard",
    botanicalName: "Beta vulgaris subsp. cicla",
    variety: "Fordhook",
    seedCount: 75,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "part-shade",
    waterNeeds: "moderate",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-pumpkin-cheese-pumpkin-001",
    commonName: "Pumpkin",
    botanicalName: "Cucurbita pepo",
    variety: "Cheese Pumpkin",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 100,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "puree", "bake"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lentil-red-001",
    commonName: "Lentil",
    botanicalName: "Lens culinaris",
    variety: "Red",
    seedCount: 200,
    germinationRate: 92,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["cook", "soup", "curry"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-okra-red-burgundy-001",
    commonName: "Okra",
    botanicalName: "Abelmoschus esculentus",
    variety: "Red Burgundy",
    seedCount: 50,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fry", "boil", "stew"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-corn-dent-batch3-001",
    commonName: "Corn, Dent",
    botanicalName: "Zea mays",
    variety: "Dent",
    seedCount: 100,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 8,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-melon-honeydew-001",
    commonName: "Melon",
    botanicalName: "Cucumis melo",
    variety: "Honeydew",
    seedCount: 50,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-radish-icicle-001",
    commonName: "Radish",
    botanicalName: "Raphanus sativus",
    variety: "Icicle",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 25,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    utahPlantingWindows: {
      spring: { start: "04-01", end: "05-31" },
      fall: { start: "08-01", end: "09-30" },
    },
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "pickle"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-parsnip-harris-model-001",
    commonName: "Parsnip",
    botanicalName: "Pastinaca sativa",
    variety: "Harris Model",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 120,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["roast", "steam"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-red-butterhead-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Red Butterhead",
    seedCount: 500,
    germinationRate: 93,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "salad"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-pinhead-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Pinhead",
    seedCount: 750,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    utahSpecificNotes: "HIGHEST SEED COUNT in the entire collection (750 seeds)!",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "salad"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-fennel-florence-001",
    commonName: "Fennel",
    botanicalName: "Foeniculum vulgare",
    variety: "Florence",
    seedCount: 50,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 65,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fresh", "roast", "steam"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-cucumber-lemon-001",
    commonName: "Cucumber",
    botanicalName: "Cucumis sativus",
    variety: "Lemon",
    seedCount: 25,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "high",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "pickle"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-congo-001",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Congo",
    seedCount: 25,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["fresh"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-beet-baby-queen-001",
    commonName: "Beet",
    botanicalName: "Beta vulgaris",
    variety: "Baby Queen",
    seedCount: 150,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["roast", "steam", "raw"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-nantes-batch3-001",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    variety: "Nantes",
    seedCount: 500,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["raw", "roast", "steam"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-radish-french-breakfast-001",
    commonName: "Radish",
    botanicalName: "Raphanus sativus",
    variety: "French Breakfast",
    seedCount: 200,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 25,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    cookingMethods: ["fresh", "pickle"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-beet-detroit-dark-red-001",
    commonName: "Beet",
    botanicalName: "Beta vulgaris",
    variety: "Detroit Dark Red",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-romaine-batch3-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Romaine",
    seedCount: 50,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 8,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-white-001",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    variety: "White",
    seedCount: 300,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-nantes-batch3-002",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    variety: "Nantes",
    seedCount: 400,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    utahSpecificNotes: "Huge carrot collection! 400 seeds.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-spinach-new-zealand-001",
    commonName: "Spinach",
    botanicalName: "Tetragonia tetragonioides",
    variety: "New Zealand",
    seedCount: 75,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 4: 5 BULK SPECIALTY PACKETS
  // ==========================================

  {
    id: "seed-corn-golden-bantam-001",
    commonName: "Sweet Corn",
    botanicalName: "Zea mays",
    variety: "Golden Bantam",
    seedCount: 100,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Bulk Specialty",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 8,
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-pea-little-marvel-001",
    commonName: "Pea",
    botanicalName: "Pisum sativum",
    variety: "Little Marvel",
    seedCount: 100,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Bulk Specialty",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    utahPlantingWindows: {
      spring: { start: "03-15", end: "04-30" },
      fall: { start: "08-01", end: "09-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fresh", "steam", "freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-pea-sugar-ann-001",
    commonName: "Pea",
    botanicalName: "Pisum sativum",
    variety: "Sugar Ann",
    seedCount: 100,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Bulk Specialty",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    utahPlantingWindows: {
      spring: { start: "03-15", end: "04-30" },
      fall: { start: "08-01", end: "09-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["fresh", "steam", "freeze"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-green-blue-lake-pole-001",
    commonName: "Bean, Green",
    botanicalName: "Phaseolus vulgaris",
    variety: "Blue Lake (Pole)",
    seedCount: 150,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Bulk Specialty",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    utahPlantingWindows: {
      spring: { start: "05-20", end: "06-30" },
    },
    frostHardiness: "frost-sensitive",
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-red-kidney-cooler-pole-001",
    commonName: "Bean",
    botanicalName: "Phaseolus vulgaris",
    variety: "Red Kidney Cooler (Pole)",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Bulk Specialty",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["dry", "bake", "soup"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 5B: 20 ADDITIONAL SURVIVAL PACKETS
  // ==========================================

  {
    id: "seed-bean-table-king-bush-001",
    commonName: "Bean, Green",
    botanicalName: "Phaseolus vulgaris",
    variety: "Table King (Bush)",
    seedCount: 100,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-dark-black-001",
    commonName: "Bean",
    botanicalName: "Phaseolus vulgaris",
    variety: "Dark (Black)",
    seedCount: 100,
    germinationRate: 86,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["dry", "soup", "rice"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-corn-dent-batch5b-001",
    commonName: "Corn, Dent",
    botanicalName: "Zea mays",
    variety: "Dent",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 8,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-long-red-lima-001",
    commonName: "Bean, Lima",
    botanicalName: "Phaseolus lunatus",
    variety: "Long Red Lima",
    seedCount: 100,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    cookingMethods: ["steam", "bake"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-mustard-old-fashioned-001",
    commonName: "Mustard",
    botanicalName: "Brassica juncea",
    variety: "Old Fashioned",
    seedCount: 200,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 40,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-crimson-sweet-001",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Crimson Sweet",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 80,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-rutgers-batch5b-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Rutgers",
    seedCount: 50,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-roma-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Roma",
    seedCount: 50,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-marketable-improved-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Marketable Improved",
    seedCount: 50,
    germinationRate: 80,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-san-marzano-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "San Marzano",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    cookingMethods: ["sauce", "can"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-summer-vegetable-001",
    commonName: "Squash",
    botanicalName: "Cucurbita pepo",
    variety: "Summer Vegetable",
    seedCount: 25,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 55,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-radish-china-rose-001",
    commonName: "Radish",
    botanicalName: "Raphanus sativus",
    variety: "China Rose",
    seedCount: 200,
    germinationRate: 86,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-pinto-001",
    commonName: "Bean, Pinto",
    botanicalName: "Phaseolus vulgaris",
    variety: "Pinto",
    seedCount: 300,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    cookingMethods: ["dry", "refried", "soup"],
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-onion-yellow-batch5b-001",
    commonName: "Onion",
    botanicalName: "Allium cepa",
    variety: "Yellow",
    seedCount: 17,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    utahSpecificNotes: "Unusual count (17 seeds) — use sparingly.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-onion-red-burgundy-001",
    commonName: "Onion",
    botanicalName: "Allium cepa",
    variety: "Red Burgundy",
    seedCount: 200,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-melon-hales-best-green-flesh-001",
    commonName: "Melon",
    botanicalName: "Cucumis melo",
    variety: "Hale's Best Green Flesh",
    seedCount: 50,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-melon-banana-001",
    commonName: "Melon",
    botanicalName: "Cucumis melo",
    variety: "Banana",
    seedCount: 50,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-vates-dwarf-blue-curled-scotch-001",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Vates, Dwarf Blue Curled Scotch",
    seedCount: 200,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-red-russian-001",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Red Russian",
    seedCount: 300,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-batch5b-unknown-001",
    commonName: "Bean",
    botanicalName: "Phaseolus vulgaris",
    variety: "Unknown — label not fully visible",
    seedCount: 75,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    notes: "Variety needs confirmation—label was partially obscured in photo",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 5C: 9 HEIRLOOM TOMATOES
  // ==========================================

  {
    id: "seed-tomato-purple-calabash-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Purple Calabash",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    flavorProfile: "Rich, complex, slightly sweet",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-azoychka-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Azoychka",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-brandywine-yellow-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Brandywine Yellow",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    flavorProfile: "Sweet, fruity, classic heirloom taste",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-sweetie-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Sweetie",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-striped-cavern-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Striped Cavern",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-black-sea-man-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Black Sea Man",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-cherokee-purple-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Cherokee Purple",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    utahSpecificNotes: "Classic heirloom. Excellent flavor but needs warm season.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    flavorProfile: "Deep, rich, slightly smoky",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-chocolate-stripes-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Chocolate Stripes",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-black-cherry-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Black Cherry",
    seedCount: 25,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 24,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    flavorProfile: "Sweet, complex, cherry-like",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  // ==========================================
  // BATCH 6: 25 SURVIVAL ESSENTIALS PACKETS
  // ==========================================

  {
    id: "seed-almond-sweet-001",
    commonName: "Almond",
    botanicalName: "Prunus dulcis",
    variety: "Sweet",
    seedCount: 30,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 365,
    startIndoors: false,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 240,
    utahZone: "6a",
    frostHardiness: "cold-hardy",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    notes: "Perennial tree crop. Long-term investment. Needs pollinator.",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-butterhead-batch6-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Butterhead",
    seedCount: 500,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 45,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-lettuce-romaine-batch6-001",
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    variety: "Romaine",
    seedCount: 250,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "part-shade",
    waterNeeds: "high",
    spacingInches: 8,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-dwarf-siberian-batch6-001",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Dwarf Siberian",
    seedCount: 250,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahZone: "6a",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-dwarf-siberian-batch6-002",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Dwarf Siberian",
    seedCount: 250,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahZone: "6a",
    utahSpecificNotes: "Second packet of Dwarf Siberian—total 750 Siberian kale seeds!",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-bean-kidney-batch6-001",
    commonName: "Bean, Kidney",
    botanicalName: "Phaseolus vulgaris",
    variety: "Kidney",
    seedCount: 75,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-batch6-unknown-001",
    commonName: "Unknown",
    botanicalName: "Unknown",
    seedCount: 25,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    notes: "Label not fully visible—variety needs confirmation",
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-onion-red-batch6-001",
    commonName: "Onion",
    botanicalName: "Allium cepa",
    variety: "Red",
    seedCount: 300,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 120,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 4,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-collard-blue-stem-001",
    commonName: "Collard",
    botanicalName: "Brassica oleracea var. viridis",
    variety: "Blue Stem",
    seedCount: 250,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-kale-variety-unknown-001",
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. acephala",
    variety: "Unknown — confirmed Dwarf Siberian upon closer inspection",
    seedCount: 250,
    germinationRate: 91,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    utahZone: "6a",
    notes: "Third Dwarf Siberian kale packet—total 750 seeds!",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-squash-butternut-001",
    commonName: "Squash",
    botanicalName: "Cucurbita moschata",
    variety: "Butternut",
    seedCount: 50,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: false,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 105,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 48,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-tomato-red-cherry-001",
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    variety: "Red Cherry",
    seedCount: 50,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 65,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 18,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-okra-towering-001",
    commonName: "Okra",
    botanicalName: "Abelmoschus esculentus",
    variety: "Towering",
    seedCount: 30,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-celery-tall-utah-001",
    commonName: "Celery",
    botanicalName: "Apium graveolens",
    variety: "Tall Utah",
    seedCount: 500,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 120,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "high",
    spacingInches: 6,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-cucumber-armenian-001",
    commonName: "Cucumber",
    botanicalName: "Cucumis melo var. flexuosus",
    variety: "Armenian",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "high",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 5,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-turnip-batch6-001",
    commonName: "Turnip",
    botanicalName: "Brassica rapa",
    variety: "Unknown — needs confirmation",
    seedCount: 400,
    germinationRate: 89,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    notes: "Variety unclear from photo—likely Purple Top or White",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-pepper-bell-batch6-001",
    commonName: "Pepper, Bell",
    botanicalName: "Capsicum annuum",
    variety: "Bell",
    seedCount: 75,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 75,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 18,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-cabbage-golden-acre-001",
    commonName: "Cabbage",
    botanicalName: "Brassica oleracea var. capitata",
    variety: "Golden Acre",
    seedCount: 150,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 65,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 12,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-brussels-sprouts-long-island-improved-001",
    commonName: "Brussels Sprouts",
    botanicalName: "Brassica oleracea var. gemmifera",
    variety: "Long Island Improved",
    seedCount: 100,
    germinationRate: 88,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 18,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-poppy-annual-001",
    commonName: "Poppy",
    botanicalName: "Papaver rhoeas",
    variety: "Annual",
    seedCount: 50,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    spacingInches: 6,
    notes: "Ornamental—not for consumption. Beautiful flowers.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-watermelon-black-diamond-001",
    commonName: "Watermelon",
    botanicalName: "Citrullus lanatus",
    variety: "Black Diamond",
    seedCount: 50,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 90,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 36,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-parsnip-hollow-crown-001",
    commonName: "Parsnip",
    botanicalName: "Pastinaca sativa",
    variety: "Hollow Crown",
    seedCount: 175,
    germinationRate: 90,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 120,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 3,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 2,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-carrot-danvers-001",
    commonName: "Carrot",
    botanicalName: "Daucus carota",
    variety: "Danvers",
    seedCount: 150,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 70,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 2,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-broccoli-budgets-001",
    commonName: "Broccoli",
    botanicalName: "Brassica oleracea var. italica",
    variety: "Budgets",
    seedCount: 100,
    germinationRate: 85,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 60,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 18,
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-mustard-florida-broadleaf-001",
    commonName: "Mustard",
    botanicalName: "Brassica juncea",
    variety: "Florida Broadleaf",
    seedCount: 600,
    germinationRate: 87,
    packagedDate: "2020-01-01",
    isHeirloom: true,
    isAnnual: true,
    source: "Survival Essentials",
    daysToMaturity: 40,
    lightRequirement: "full-sun",
    waterNeeds: "moderate",
    spacingInches: 6,
    utahSpecificNotes: "HUGE COUNT—600 seeds! Perfect for continuous greens.",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 4,
    createdAt: "2026-07-02T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
    plantingHistory: [],
  },

  {
    id: "seed-yarrow-achillea-001",
    commonName: "Yarrow",
    botanicalName: "Achillea millefolium",
    variety: "Mixed Heirloom",
    seedCount: 200,
    germinationRate: 86,
    packagedDate: "2020-01-01",
    storageLocation: "Cool storage",
    isHeirloom: true,
    isAnnual: false,
    source: "Survival Essentials",
    daysToMaturity: 60,
    daysToGermination: 10,
    startIndoors: true,
    lightRequirement: "full-sun",
    waterNeeds: "low",
    soilType: "Well-draining, tolerates poor soil",
    spacingInches: 18,
    utahPlantingWindows: {
      spring: { start: "03-01", end: "05-30" },
      fall: { start: "08-15", end: "10-15" },
    },
    frostHardiness: "cold-hardy",
    utahZone: "3",
    utahSpecificNotes: "Utah native ally—thrives in high desert. Drought tolerant once established. Attracts beneficial insects (parasitic wasps, hover flies). Great for pollinators. Can spread via rhizomes—divide every 2-3 years.",
    harvestTiming: "Cut when flowers fully open but petals still hold",
    harvestSeason: "June-September",
    yieldPerPlant: "Multiple stems per plant, rebloom if deadheaded",
    canSaveSeed: true,
    seedStorageMethod: "cool-dry",
    estimatedShelfLife: 3,
    culinaryUses: ["tea", "tincture", "dried flowers", "fresh bouquets"],
    medicinalProperties: [
      "Traditional wound healer (stops bleeding)",
      "Anti-inflammatory",
      "Fever reduction",
      "Digestive support",
    ],
    commonCuisines: ["Herbal", "Medicinal"],
    companionPlants: ["lavender", "rosemary", "thyme", "bee balm", "dill"],
    attractsPollinators: true,
    attractsBeneficialInsects: true,
    createdAt: "2026-07-06T00:00:00Z",
    updatedAt: "2026-07-06T00:00:00Z",
    plantingHistory: [],
  } as unknown as SeedPacket,
];


// Export as default for easy import
export default completeSeedVaultDatabase;
